apiVersion: kuudra.io/v1alpha1
kind: EventSource
metadata: {namespace: process-control-demo, name: trigger}
spec:
  component: kuudra-official/session-probe/session-probe-source
  desiredState: running
  options:
    eventType: process-control.trigger
    initialDelayMillis: 5000
    maxEvents: 1
---
apiVersion: kuudra.io/v1alpha1
kind: Ingress
metadata: {namespace: process-control-demo, name: ingress}
spec:
  component: kuudra-official/default/plain-ingress
  desiredState: active
  options: {groupKey: process-control}
---
apiVersion: kuudra.io/v1alpha1
kind: EventHandler
metadata: {namespace: process-control-demo, name: process-control}
spec:
  component: actforever/process-control/process-control
  desiredState: running
  options:
    allowElevation: true
    targets:
      ping:
        executablePath: 'C:\Windows\System32\PING.EXE'
    action: SUSPEND
    target: ping
    durationMillis: 2000
    defaultDurationMillis: 10000
    maxDurationMillis: 60000
---
apiVersion: kuudra.io/v1alpha1
kind: Flow
metadata: {namespace: process-control-demo, name: process-control-safe}
spec:
  imports:
    trigger: {kind: EventSource, name: trigger}
    ingress: {kind: Ingress, name: ingress}
    process-control: {kind: EventHandler, name: process-control}
  edges:
    - {from: trigger, to: ingress}
    - {from: ingress, to: process-control}
