package io.github.actforever.kuudra.macro;

import io.github.actforever.kuudra.api.KuudraException;
import io.github.actforever.kuudra.api.context.ContextCodecs;
import io.github.actforever.kuudra.interaction.*;
import java.util.*;

public final class MacroCodec {
    private static final int MAX_DEPTH=32;
    private MacroCodec(){ }
    public static MacroProgramDefinition decode(Map<String,Object> configuration){long max=number(configuration.getOrDefault("maxTotalSteps",10_000),"maxTotalSteps");long marker=number(configuration.getOrDefault("syntheticMarkerLifetimeMillis",500),"syntheticMarkerLifetimeMillis");return new MacroProgramDefinition(parseSteps(list(configuration.get("steps"),"steps"),0),max,marker);}
    public static Map<String,Object> encode(MacroProgramDefinition program){List<Object> values=program.steps().stream().map(MacroCodec::encodeStep).toList();return Map.of("steps",values,"maxTotalSteps",program.maxTotalSteps(),"syntheticMarkerLifetimeMillis",program.syntheticMarkerLifetimeMillis());}
    private static List<MacroStep> parseSteps(List<?> values,int depth){if(depth>MAX_DEPTH)throw invalid("Macro nesting exceeds "+MAX_DEPTH);List<MacroStep> out=new ArrayList<>();for(Object value:values){Map<String,Object> item=map(value,"step");String action=text(item.get("action"),"step.action");out.add(switch(action){
        case "keyPress"->new MacroStep.KeyPress(decode(item.get("key"),KeySpec.class,"key"));case "keyRelease"->new MacroStep.KeyRelease(decode(item.get("key"),KeySpec.class,"key"));case "keyTap"->new MacroStep.KeyTap(decode(item.get("key"),KeySpec.class,"key"),number(item.getOrDefault("holdMillis",50),"holdMillis"));
        case "type"->new MacroStep.TypeKeys(list(item.get("keys"),"keys").stream().map(v->decode(v,KeySpec.class,"keys[]")).toList(),item.containsKey("modifiers")?list(item.get("modifiers"),"modifiers").stream().map(v->decode(v,ModifierKey.class,"modifiers[]")).toList():List.of(),number(item.getOrDefault("holdMillis",25),"holdMillis"),number(item.getOrDefault("intervalMillis",0),"intervalMillis"));
        case "mousePress"->new MacroStep.MousePress(decode(item.get("button"),MouseButtonSpec.class,"button"));case "mouseRelease"->new MacroStep.MouseRelease(decode(item.get("button"),MouseButtonSpec.class,"button"));case "mouseClick"->new MacroStep.MouseClick(decode(item.get("button"),MouseButtonSpec.class,"button"),number(item.getOrDefault("holdMillis",50),"holdMillis"));case "mouseMove"->new MacroStep.MouseMove(decode(item.get("position"),ScreenPosition.class,"position"));case "mouseWheel"->new MacroStep.MouseWheel(decode(item.get("wheel"),MouseWheelSpec.class,"wheel"));case "sleep"->new MacroStep.Sleep(number(item.get("durationMillis"),"durationMillis"));
        case "if"->new MacroStep.If(condition(map(item.get("condition"),"condition")),parseSteps(list(item.get("then"),"then"),depth+1),item.containsKey("else")?parseSteps(list(item.get("else"),"else"),depth+1):List.of());
        case "loop"->{Long count=item.containsKey("count")?number(item.get("count"),"count"):null;Long maximum=item.containsKey("maxIterations")?number(item.get("maxIterations"),"maxIterations"):count;if(maximum==null||maximum<0)throw invalid("loop requires count or maxIterations");yield new MacroStep.Loop(count,maximum,item.containsKey("while")?condition(map(item.get("while"),"while")):null,parseSteps(list(item.get("steps"),"steps"),depth+1));}
        case "break"->new MacroStep.Break(item.containsKey("when")?condition(map(item.get("when"),"when")):null);case "return"->new MacroStep.Return(item.containsKey("when")?condition(map(item.get("when"),"when")):null);case "cancelSession"->new MacroStep.CancelSession(String.valueOf(item.getOrDefault("reason","macro-requested")),item.containsKey("when")?condition(map(item.get("when"),"when")):null);case "emit"->new MacroStep.Emit(text(item.get("eventType"),"eventType"),Boolean.TRUE.equals(decode(item.getOrDefault("copyInputData",false),Boolean.class,"copyInputData")),item.containsKey("data")?map(item.get("data"),"data"):Map.of());default->throw invalid("Unsupported macro action: "+action);});}return List.copyOf(out);}
    private static MacroCondition condition(Map<String,Object> value){String ref=text(value.get("ref"),"condition.ref");MacroCondition.Operator op=MacroCondition.Operator.valueOf(String.valueOf(value.getOrDefault("operator","TRUTHY")).toUpperCase(Locale.ROOT));return MacroCondition.ref(ref,op,value.get("value"));}
    private static Object encodeStep(MacroStep step){Map<String,Object> out=new LinkedHashMap<>();if(step instanceof MacroStep.KeyPress s){out.put("action","keyPress");out.put("key",s.key());}else if(step instanceof MacroStep.KeyRelease s){out.put("action","keyRelease");out.put("key",s.key());}else if(step instanceof MacroStep.KeyTap s){out.put("action","keyTap");out.put("key",s.key());out.put("holdMillis",s.holdMillis());}else if(step instanceof MacroStep.TypeKeys s){out.put("action","type");out.put("keys",s.keys());out.put("modifiers",s.modifiers());out.put("holdMillis",s.holdMillis());out.put("intervalMillis",s.intervalMillis());}else if(step instanceof MacroStep.MousePress s){out.put("action","mousePress");out.put("button",s.button());}else if(step instanceof MacroStep.MouseRelease s){out.put("action","mouseRelease");out.put("button",s.button());}else if(step instanceof MacroStep.MouseClick s){out.put("action","mouseClick");out.put("button",s.button());out.put("holdMillis",s.holdMillis());}else if(step instanceof MacroStep.MouseMove s){out.put("action","mouseMove");out.put("position",s.position());}else if(step instanceof MacroStep.MouseWheel s){out.put("action","mouseWheel");out.put("wheel",s.wheel());}else if(step instanceof MacroStep.Sleep s){out.put("action","sleep");out.put("durationMillis",s.durationMillis());}else if(step instanceof MacroStep.If s){out.put("action","if");out.put("condition",encodeCondition(s.condition()));out.put("then",s.thenSteps().stream().map(MacroCodec::encodeStep).toList());if(!s.elseSteps().isEmpty())out.put("else",s.elseSteps().stream().map(MacroCodec::encodeStep).toList());}else if(step instanceof MacroStep.Loop s){out.put("action","loop");if(s.count()!=null)out.put("count",s.count());out.put("maxIterations",s.maxIterations());if(s.condition()!=null)out.put("while",encodeCondition(s.condition()));out.put("steps",s.steps().stream().map(MacroCodec::encodeStep).toList());}else if(step instanceof MacroStep.Break s){out.put("action","break");if(s.condition()!=null)out.put("when",encodeCondition(s.condition()));}else if(step instanceof MacroStep.Return s){out.put("action","return");if(s.condition()!=null)out.put("when",encodeCondition(s.condition()));}else if(step instanceof MacroStep.CancelSession s){out.put("action","cancelSession");out.put("reason",s.reason());if(s.condition()!=null)out.put("when",encodeCondition(s.condition()));}else if(step instanceof MacroStep.Emit s){out.put("action","emit");out.put("eventType",s.eventType());out.put("copyInputData",s.copyInputData());out.put("data",s.data());}else throw invalid("Encoding is not implemented for "+step.getClass().getSimpleName());return Map.copyOf(out);}
    private static Map<String,Object> encodeCondition(MacroCondition condition){Map<String,Object> out=new LinkedHashMap<>();out.put("ref",condition.referenceExpression());out.put("operator",condition.operator().name());if(condition.expected()!=null)out.put("value",condition.expected());return Map.copyOf(out);}
    @SuppressWarnings("unchecked")private static Map<String,Object> map(Object value,String path){if(!(value instanceof Map<?,?> input))throw invalid(path+" must be an object");Map<String,Object> out=new LinkedHashMap<>();input.forEach((k,v)->{if(!(k instanceof String s))throw invalid(path+" keys must be strings");out.put(s,v);});return Map.copyOf(out);}private static List<?> list(Object value,String path){if(!(value instanceof List<?> list))throw invalid(path+" must be an array");return list;}private static String text(Object value,String path){if(!(value instanceof String s)||s.isBlank())throw invalid(path+" must be text");return s;}private static long number(Object value,String path){if(!(value instanceof Number n))throw invalid(path+" must be a number");return n.longValue();}private static <T>T decode(Object value,Class<T> type,String path){if(value==null)throw invalid(path+" is required");try{return ContextCodecs.defaultCodec().decode(value,type);}catch(RuntimeException e){throw new KuudraException("Invalid macro value at "+path+": expected "+type.getSimpleName(),e);}}private static KuudraException invalid(String message){return new KuudraException(message);}
}
