id = "macro-kotlin"
namespace = "actforever"
version = "0.2.0-alpha-1"
entrypoint = "io.github.actforever.kuudra.macrokotlin.KotlinMacroPlugin"

[[dependencies]]
namespace = "actforever"
pluginId = "macro-spec"
mandatory = true
versionRange = "[0.2.0-alpha-1,0.3.0)"
