package io.github.actforever.kuudra.interaction;

/** Logical key names. UNKNOWN preserves forward compatibility with provider-specific codes. */
public enum KeyCode {
    ESCAPE,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,
    BACKQUOTE,
    NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9, NUM_0,
    MINUS, EQUALS, BACKSPACE, TAB, CAPS_LOCK,
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    OPEN_BRACKET, CLOSE_BRACKET, BACK_SLASH, SEMICOLON, QUOTE, ENTER,
    COMMA, PERIOD, SLASH, SPACE,
    PRINT_SCREEN, SCROLL_LOCK, PAUSE, INSERT, DELETE, HOME, END, PAGE_UP, PAGE_DOWN,
    UP, LEFT, CLEAR, RIGHT, DOWN,
    NUM_LOCK, SEPARATOR,
    SHIFT, CONTROL, ALT, META, CONTEXT_MENU,
    POWER, SLEEP, WAKE,
    MEDIA_PLAY, MEDIA_STOP, MEDIA_PREVIOUS, MEDIA_NEXT, MEDIA_SELECT, MEDIA_EJECT,
    VOLUME_MUTE, VOLUME_UP, VOLUME_DOWN,
    APP_MAIL, APP_CALCULATOR, APP_MUSIC, APP_PICTURES,
    BROWSER_SEARCH, BROWSER_HOME, BROWSER_BACK, BROWSER_FORWARD,
    BROWSER_STOP, BROWSER_REFRESH, BROWSER_FAVORITES,
    KATAKANA, FURIGANA, KANJI, HIRAGANA, YEN,
    SUN_HELP, SUN_STOP, SUN_PROPS, SUN_FRONT, SUN_OPEN, SUN_FIND,
    SUN_AGAIN, SUN_UNDO, SUN_COPY, SUN_INSERT, SUN_CUT,
    UNKNOWN
}
