apiVersion: kuudra.io/v1alpha1
kind: Flow
metadata:
  namespace: macro
  name: keyboard-to-log
spec:
  imports:
    keyboard:
      kind: EventSource
      name: keyboard
    ingress:
      kind: Ingress
      name: input-ingress
    logger:
      kind: EventHandler
      name: input-logger
  edges:
    - from: keyboard
      to: ingress
    - from: ingress
      to: logger
