<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.actforever</groupId>
        <artifactId>kuudra-official-plugins</artifactId>
        <version>0.2.0-alpha-1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>kuudra-conditional-boundary-plugin</artifactId>
    <dependencies>
        <dependency>
            <groupId>io.github.actforever</groupId>
            <artifactId>kuudra-api</artifactId>
            <version>${kuudra.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.actforever</groupId>
            <artifactId>kuudra-plugin</artifactId>
            <version>${kuudra.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
