apiVersion: kuudra.io/v1alpha1
kind: Ingress
metadata:
  namespace: hello-world-demo
  name: ingress
spec:
  component: kuudra-official/plain-ingress
  desiredState: active
  options:
    groupKey: "${event#hello-world.message}"
    policy: SERIAL
    groupScope: FLOW_BINDING
    maxParallelSessions: 1
    queueCapacity: 32
