apiVersion: kuudra.io/v1alpha1
kind: EventHandler
metadata:
  namespace: hello-world-demo
  name: logger
spec:
  component: kuudra-official/event-logger
  desiredState: running
  options:
    level: INFO
    message: "received ${event#hello-world.message}"
    includeData: true
